
#█░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
#█▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█


# Set your personal hyprland configuration here
# for sample file, please refer https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2
#
#
monitor=DP-2,highrr, 0x0,1
monitor=HDMI-A-1,highrr,0x1440,1
monitor=DP-1,preferred,2580x0,1,transform,1
